name: Deploy Database to Production

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'

jobs:
  deploy-production:
    name: Deploy to Production Database
    runs-on: ubuntu-latest

    # Requires manual approval before deployment
    environment:
      name: production
      url: https://supabase.com/dashboard/project/moqzugvlwzdotgnjmndd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Verify migrations
        run: |
          echo "📋 Checking migration files..."
          ls -la supabase/migrations/
          echo ""
          echo "🔍 Latest migration:"
          ls -t supabase/migrations/*.sql | head -1 | xargs cat

      - name: Link to Supabase project
        run: npx supabase link --project-ref moqzugvlwzdotgnjmndd
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push migrations to production
        run: npx supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Notify success
        if: success()
        run: |
          echo "✅ Database migrations deployed successfully to production!"
          echo "🔗 View at: https://supabase.com/dashboard/project/moqzugvlwzdotgnjmndd"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ Database migration deployment failed!"
          echo "Please check the logs and verify migration files."
